---
abstract: 'Format CN&EN pages for typesetting'
author:
  - woosley.xu
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300003, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Format-CN
requires:
  Encode: 0
  Sub::Exporter: 0
resources:
  repository: git://github.com/woosley/Format-CN.git
version: 0.01
